name: Readme activity

on:
 schedule:
  - cron: "*/5 * * * *"
 workflow_dispatch:

jobs:
 activity:
  runs-on: ubuntu-latest
  name: âœ¨ README Activity
  steps:
   - uses: actions/checkout@v2
   - uses: igorkowalczykbot/github-activity@master
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
