name: Update README with latest blog

on:
 schedule:
  - cron: "*/5 * * * *"

jobs:
 blog:
  runs-on: ubuntu-latest
  steps:
   - name: [Blog] üéè Fetch repo
     uses: actions/checkout@master
     with:
      fetch-depth: 1
   - name: [Blog] ‚ú® Create README.md
     run: |
      cd ${GITHUB_WORKSPACE}/
      npm i
      node src/blog.js
   - name: [Blog] üöÄ Deploy
     run: |
      git config user.name Igor Kowalczyk
      git config user.email xxmajonezxx@gmail.com
      git add .
      git commit -am "[Bot] Update blog posts"
      git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
